name: Front CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build front-end
        run: npm run build

      - name: Run tests
        run: npm test || true

  # docker:
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Log in to the Container registry
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GHCR_PASSWORD }}

  #     - name: Build Docker image
  #       run: |
  #         docker build -t ghcr.io/yuram8/teachua-frontend:latest .

  #     - name: Push Docker image to GitHub Container Registry
  #       run: |
  #         docker push ghcr.io/yuram8/teachua-frontend:latest 




    
